In [36]:
from sklearn.datasets import load_boston

In [37]:
boston = load_boston()
bos=boston.data
tar=boston.target

In [38]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
import xgboost as xgb
from sklearn import neighbors


In [39]:
X_train, X_test, Y_train, Y_test = train_test_split(bos, tar, test_size = 0.1, random_state = 0)

In [40]:
from sklearn import linear_model,tree,svm,ensemble
regressors=[
    linear_model.LinearRegression(),#
    linear_model.Ridge(),#
    linear_model.Lasso(),#
    linear_model.ElasticNet(),#
    linear_model.BayesianRidge(),#
    linear_model.RANSACRegressor(),
    svm.SVR(),
    ensemble.GradientBoostingRegressor(),#
    tree.DecisionTreeRegressor(),
    ensemble.RandomForestRegressor(),#
    xgb.XGBRegressor(),#
    neighbors.KNeighborsRegressor(),#
    ensemble.AdaBoostRegressor()##
]

In [41]:
for reg in regressors:
    reg.fit(X_train,Y_train)
    name=reg.__class__.__name__
    print('='*30)
    print(name)
    predictions=reg.predict(X_test)
    rmse=np.sqrt(mean_squared_error(Y_test,predictions))
    print("RMSError is: {}".format(rmse))

LinearRegression
RMSError is: 6.458354874761972
Ridge
RMSError is: 6.538352930974199
Lasso
RMSError is: 6.609361766879547
ElasticNet
RMSError is: 6.557164132740225
BayesianRidge
RMSError is: 6.632315057734658
RANSACRegressor
RMSError is: 8.23881256020588
SVR
RMSError is: 9.19308348246483
GradientBoostingRegressor
RMSError is: 4.5430079464525965
DecisionTreeRegressor
RMSError is: 5.61182225481241
RandomForestRegressor
RMSError is: 5.069441899900875
XGBRegressor
RMSError is: 4.684212166768228
KNeighborsRegressor
RMSError is: 7.231886906976222
AdaBoostRegressor
RMSError is: 6.357589589277343


In [104]:
#select best features for linear regression

from sklearn import feature_selection
from sklearn import pipeline
from sklearn.grid_search import GridSearchCV



class MyPipe(pipeline.Pipeline):

    def fit(self, X, y=None, **fit_params):
        """Calls last elements .coef_ method.
        Based on the sourcecode for decision_function(X).
        Link: https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/pipeline.py
        ----------
        """
        super(MyPipe, self).fit(X, y, **fit_params)
        self.coef_ = self.steps[-1][-1].coef_
        return self



xx=linear_model.LinearRegression()

selector = feature_selection.RFE(xx)
selector.fit(X_train,np.ravel(Y_train))
ypredd=selector.predict(X_test)
print("no. of features selected=",selector.n_features_)
print("the array of features----1 represents the selected feautures",selector.ranking_)
#rmse=np.sqrt(mean_squared_error(Y_test,ypredd))
#selector.n_features_


no. of features selected= 6
the array of features----1 represents the selected feautures [2 4 8 1 1 1 6 1 3 5 1 7 1]


In [92]:
#select best parameters for Knearestneighbours regression

#it may take A LOOOOT  of time depending on the dataset

from sklearn.neighbors import KNeighborsRegressor
from sklearn import feature_selection
from sklearn import pipeline
from sklearn.grid_search import GridSearchCV


class MyPipe(pipeline.Pipeline):

    def fit(self, X, y=None, **fit_params):
        """Calls last elements .coef_ method.
        Based on the sourcecode for decision_function(X).
        Link: https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/pipeline.py
        ----------
        """
        super(MyPipe, self).fit(X, y, **fit_params)
        self.coef_ = self.steps[-1][-1].coef_
        return self



#X, y = make_friedman1(n_samples=50, n_features=10, random_state=0)

# Without Pipeline
clf1 = KNeighborsRegressor()
#selector1 = feature_selection.RFE(clf1)
clf = GridSearchCV(clf1, param_grid={'n_neighbors': [
1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,30,35,40,45,50,100],'leaf_size': [
1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,30,35,40,45,50,100],'weights':['uniform','distance'],'algorithm' : ['auto', 'ball_tree', 'kd_tree', 'brute'],'p':[1,2]},cv=10)
print("RUNNING")

clf.fit(X_train,np.ravel(Y_train))

print("\n\n\n\n")
print(clf.best_estimator_)
print(clf.best_estimator_.ranking_)

clf.best_estimator_.n_features_

print("\n\n\n\n")
print("\n\n\n\n")
print("\n\n\n\n")
print(clf.grid_scores_)








RUNNING


KeyboardInterrupt: 

In [98]:
#select best parameters and features for ridge regression
from sklearn import feature_selection
from sklearn import pipeline
from sklearn.grid_search import GridSearchCV
from sklearn import linear_model


class MyPipe(pipeline.Pipeline):

    def fit(self, X, y=None, **fit_params):
        """Calls last elements .coef_ method.
        Based on the sourcecode for decision_function(X).
        Link: https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/pipeline.py
        ----------
        """
        super(MyPipe, self).fit(X, y, **fit_params)
        self.coef_ = self.steps[-1][-1].coef_
        return self



#X, y = make_friedman1(n_samples=50, n_features=10, random_state=0)

# Without Pipeline
clf2 = linear_model.Ridge()

selector2 = feature_selection.RFE(clf2)
clf3 = GridSearchCV(selector2, param_grid={"estimator__random_state":[0],"estimator__alpha":[0.5,0.6,0.7,0.8,0.9,1.0,1.1,1.2,1.3,1.4,1.5,1.6,1.7,1.8,1.9,2.0]},cv=10)
print("RUNNING")

clf3.fit(X_train,np.ravel(Y_train))

print("BEST PARAMETERS\n")
print(clf3.best_estimator_)
print("\nFEATURES_RANKING")
print(clf3.best_estimator_.n_features_,"feautres selected")


print(clf3.best_estimator_.ranking_)
print("\n\n\n\n")
print("\n\n\n\n")
print((clf3.grid_scores_))








RUNNING
BEST PARAMETERS

RFE(estimator=Ridge(alpha=0.5, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=0, solver='auto', tol=0.001),
  n_features_to_select=None, step=1, verbose=0)

FEATURES_RANKING
6 feautres selected
[3 5 2 1 1 1 7 1 4 6 1 8 1]










[mean: 0.70917, std: 0.10465, params: {'estimator__alpha': 0.5, 'estimator__random_state': 0}, mean: 0.70894, std: 0.10495, params: {'estimator__alpha': 0.6, 'estimator__random_state': 0}, mean: 0.70869, std: 0.10522, params: {'estimator__alpha': 0.7, 'estimator__random_state': 0}, mean: 0.70843, std: 0.10547, params: {'estimator__alpha': 0.8, 'estimator__random_state': 0}, mean: 0.70816, std: 0.10569, params: {'estimator__alpha': 0.9, 'estimator__random_state': 0}, mean: 0.70789, std: 0.10589, params: {'estimator__alpha': 1.0, 'estimator__random_state': 0}, mean: 0.70761, std: 0.10608, params: {'estimator__alpha': 1.1, 'estimator__random_state': 0}, mean: 0.70734, std: 0.10625, params: {'estimator__

In [99]:
#select best parameters and features for Lasso regression
from sklearn import feature_selection
from sklearn import pipeline
from sklearn.grid_search import GridSearchCV
from sklearn import linear_model


class MyPipe(pipeline.Pipeline):

    def fit(self, X, y=None, **fit_params):
        """Calls last elements .coef_ method.
        Based on the sourcecode for decision_function(X).
        Link: https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/pipeline.py
        ----------
        """
        super(MyPipe, self).fit(X, y, **fit_params)
        self.coef_ = self.steps[-1][-1].coef_
        return self



#X, y = make_friedman1(n_samples=50, n_features=10, random_state=0)

# Without Pipeline
clf2 = linear_model.Lasso()

selector2 = feature_selection.RFE(clf2)
clf3 = GridSearchCV(selector2, param_grid={"estimator__random_state":[0],"estimator__alpha":[0.5,0.6,0.7,0.8,0.9,1.0,1.1,1.2,1.3,1.4,1.5,1.6,1.7,1.8,1.9,2.0]},cv=10)
print("RUNNING")

clf3.fit(X_train,np.ravel(Y_train))

print("BEST PARAMETERS\n")
print(clf3.best_estimator_)
print("\nFEATURES_RANKING")
print(clf3.best_estimator_.n_features_,"feautres selected")


print(clf3.best_estimator_.ranking_)
print("\n\n\n\n")
print("\n\n\n\n")
print((clf3.grid_scores_))








RUNNING
BEST PARAMETERS

RFE(estimator=Lasso(alpha=0.5, copy_X=True, fit_intercept=True, max_iter=1000,
   normalize=False, positive=False, precompute=False, random_state=0,
   selection='cyclic', tol=0.0001, warm_start=False),
  n_features_to_select=None, step=1, verbose=0)

FEATURES_RANKING
6 feautres selected
[1 2 1 8 7 1 6 1 3 4 1 5 1]










[mean: 0.68538, std: 0.08550, params: {'estimator__alpha': 0.5, 'estimator__random_state': 0}, mean: 0.68211, std: 0.08502, params: {'estimator__alpha': 0.6, 'estimator__random_state': 0}, mean: 0.67310, std: 0.08908, params: {'estimator__alpha': 0.7, 'estimator__random_state': 0}, mean: 0.66839, std: 0.09125, params: {'estimator__alpha': 0.8, 'estimator__random_state': 0}, mean: 0.66268, std: 0.09367, params: {'estimator__alpha': 0.9, 'estimator__random_state': 0}, mean: 0.65610, std: 0.09659, params: {'estimator__alpha': 1.0, 'estimator__random_state': 0}, mean: 0.64867, std: 0.09996, params: {'estimator__alpha': 1.1, 'estimator__random_s

In [103]:
#select best parameters and features for Elastic net regression
from sklearn import feature_selection
from sklearn import pipeline
from sklearn.grid_search import GridSearchCV
from sklearn import linear_model


class MyPipe(pipeline.Pipeline):

    def fit(self, X, y=None, **fit_params):
        """Calls last elements .coef_ method.
        Based on the sourcecode for decision_function(X).
        Link: https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/pipeline.py
        ----------
        """
        super(MyPipe, self).fit(X, y, **fit_params)
        self.coef_ = self.steps[-1][-1].coef_
        return self



#X, y = make_friedman1(n_samples=50, n_features=10, random_state=0)

# Without Pipeline
clf2 = linear_model.ElasticNet()

selector2 = feature_selection.RFE(clf2)
clf3 = GridSearchCV(selector2, param_grid={"estimator__random_state":[0],"estimator__alpha":[0.2,0.1,0.05,0.09,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0,1.1,1.2,1.3,1.4,1.5,1.6,1.7,1.8,1.9,2.0]},cv=10)
print("RUNNING")

clf3.fit(X_train,np.ravel(Y_train))

print("BEST PARAMETERS\n")
print(clf3.best_estimator_)
print("\nFEATURES_RANKING")
print(clf3.best_estimator_.n_features_,"feautres selected")


print(clf3.best_estimator_.ranking_)
print("\n\n\n\n")
print("\n\n\n\n")
print((clf3.grid_scores_))








RUNNING
BEST PARAMETERS

RFE(estimator=ElasticNet(alpha=0.09, copy_X=True, fit_intercept=True, l1_ratio=0.5,
      max_iter=1000, normalize=False, positive=False, precompute=False,
      random_state=0, selection='cyclic', tol=0.0001, warm_start=False),
  n_features_to_select=None, step=1, verbose=0)

FEATURES_RANKING
6 feautres selected
[2 3 1 1 8 1 4 1 5 6 1 7 1]










[mean: 0.69625, std: 0.08199, params: {'estimator__alpha': 0.2, 'estimator__random_state': 0}, mean: 0.69691, std: 0.08945, params: {'estimator__alpha': 0.1, 'estimator__random_state': 0}, mean: 0.69589, std: 0.10319, params: {'estimator__alpha': 0.05, 'estimator__random_state': 0}, mean: 0.69762, std: 0.09102, params: {'estimator__alpha': 0.09, 'estimator__random_state': 0}, mean: 0.69323, std: 0.08110, params: {'estimator__alpha': 0.3, 'estimator__random_state': 0}, mean: 0.69062, std: 0.07970, params: {'estimator__alpha': 0.4, 'estimator__random_state': 0}, mean: 0.68645, std: 0.08048, params: {'estimator__alpha

In [108]:
#select best features for BayesianRidge
from sklearn import feature_selection
from sklearn import pipeline
from sklearn.grid_search import GridSearchCV
from sklearn import linear_model


class MyPipe(pipeline.Pipeline):

    def fit(self, X, y=None, **fit_params):
        """Calls last elements .coef_ method.
        Based on the sourcecode for decision_function(X).
        Link: https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/pipeline.py
        ----------
        """
        super(MyPipe, self).fit(X, y, **fit_params)
        self.coef_ = self.steps[-1][-1].coef_
        return self



#X, y = make_friedman1(n_samples=50, n_features=10, random_state=0)

# Without Pipeline
clf2 = linear_model.BayesianRidge()


clf3 = feature_selection.RFE(clf2)
print("RUNNING")

clf3.fit(X_train,np.ravel(Y_train))

print("\nFEATURES_RANKING")
print(clf3.n_features_,"feautres selected")


print(clf3.ranking_)
print("\n\n\n\n")
print("\n\n\n\n")








RUNNING

FEATURES_RANKING
6 feautres selected
[3 4 2 1 1 1 6 1 5 7 1 8 1]












In [112]:
#select best parameters and features for GRADIENT BOOSTING REGRESSOR
#THIS WILL TAKE A LOOOOOOOOOOOOOOOOOOOOOOOOT OF TIME 15-30 MIN MAYBE MORE DEPENDING ON DATASET
#Took 20 min on this dataset
from sklearn import feature_selection
from sklearn import pipeline
from sklearn.grid_search import GridSearchCV
from sklearn import linear_model


class MyPipe(pipeline.Pipeline):

    def fit(self, X, y=None, **fit_params):
        """Calls last elements .coef_ method.
        Based on the sourcecode for decision_function(X).
        Link: https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/pipeline.py
        ----------
        """
        super(MyPipe, self).fit(X, y, **fit_params)
        self.coef_ = self.steps[-1][-1].coef_
        return self



#X, y = make_friedman1(n_samples=50, n_features=10, random_state=0)

# Without Pipeline
clf2 =  ensemble.GradientBoostingRegressor()


selector2 = feature_selection.RFE(clf2)
clf3 = GridSearchCV(selector2, param_grid={"estimator__max_features":["auto","sqrt","log2"],"estimator__random_state":[0],"estimator__loss":['ls', 'lad', 'huber', 'quantile'],"estimator__n_estimators":[50,100,150,200,250,300,350,400]},cv=10)
print("RUNNING")

clf3.fit(X_train,np.ravel(Y_train))

print("BEST PARAMETERS\n")
print(clf3.best_estimator_)
print("\nFEATURES_RANKING")
print(clf3.best_estimator_.n_features_,"feautres selected")


print(clf3.best_estimator_.ranking_)
print("\n\n\n\n")
print("\n\n\n\n")
print((clf3.grid_scores_))


"""
learning_rate : float, optional (default=0.1)


max_depth : integer, optional (default=3)


(max_features * n_features)` features are considered at each
      split.
    - If "auto", then `max_features=n_features`.
    - If "sqrt", then `max_features=sqrt(n_features)`.
    - If "log2", then `max_features=log2(n_features)`.
    - If None, then `max_features=n_features`.
"""

RUNNING
BEST PARAMETERS

RFE(estimator=GradientBoostingRegressor(alpha=0.9, criterion='friedman_mse', init=None,
             learning_rate=0.1, loss='huber', max_depth=3,
             max_features='log2', max_leaf_nodes=None,
             min_impurity_decrease=0.0, min_impurity_split=None,
             min_samples_leaf=1, min_samples_split=2,
             min_weight_fraction_leaf=0.0, n_estimators=350,
             presort='auto', random_state=0, subsample=1.0, verbose=0,
             warm_start=False),
  n_features_to_select=None, step=1, verbose=0)

FEATURES_RANKING
6 feautres selected
[1 7 3 8 1 1 1 1 6 4 5 2 1]










[mean: 0.83180, std: 0.12991, params: {'estimator__loss': 'ls', 'estimator__max_features': 'auto', 'estimator__n_estimators': 50, 'estimator__random_state': 0}, mean: 0.82471, std: 0.13480, params: {'estimator__loss': 'ls', 'estimator__max_features': 'auto', 'estimator__n_estimators': 100, 'estimator__random_state': 0}, mean: 0.83138, std: 0.13519, params: {'estim

'\nlearning_rate : float, optional (default=0.1)\n\n\nmax_depth : integer, optional (default=3)\n\n\n(max_features * n_features)` features are considered at each\n      split.\n    - If "auto", then `max_features=n_features`.\n    - If "sqrt", then `max_features=sqrt(n_features)`.\n    - If "log2", then `max_features=log2(n_features)`.\n    - If None, then `max_features=n_features`.\n'

In [116]:
#select best parameters and features for ADA BOOSTING REGRESSOR
#it may take A LOOOOOOOT  of time depending on the dataset
#>30 mins on this dataset
from sklearn import feature_selection
from sklearn import pipeline
from sklearn.grid_search import GridSearchCV
from sklearn import linear_model


class MyPipe(pipeline.Pipeline):

    def fit(self, X, y=None, **fit_params):
        """Calls last elements .coef_ method.
        Based on the sourcecode for decision_function(X).
        Link: https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/pipeline.py
        ----------
        """
        super(MyPipe, self).fit(X, y, **fit_params)
        self.coef_ = self.steps[-1][-1].coef_
        return self



#X, y = make_friedman1(n_samples=50, n_features=10, random_state=0)

# Without Pipeline
clf2 =  ensemble.AdaBoostRegressor()



selector2 = feature_selection.RFE(clf2)
clf3 = GridSearchCV(selector2, param_grid={"estimator__loss":['linear', 'square'],"estimator__random_state":[0],"estimator__learning_rate":[0.1,0.5,1,1.5,2.0,2.5,3.0],"estimator__n_estimators":[50,100,150,200,250,300,350,400]},cv=4)
print("RUNNING")

clf3.fit(X_train,np.ravel(Y_train))

print("BEST PARAMETERS\n")
print(clf3.best_estimator_)
print("\nFEATURES_RANKING")
print(clf3.best_estimator_.n_features_,"feautres selected")


print(clf3.best_estimator_.ranking_)
print("\n\n\n\n")
print("\n\n\n\n")
print((clf3.grid_scores_))


RUNNING
BEST PARAMETERS

RFE(estimator=AdaBoostRegressor(base_estimator=None, learning_rate=2.5, loss='linear',
         n_estimators=50, random_state=0),
  n_features_to_select=None, step=1, verbose=0)

FEATURES_RANKING
6 feautres selected
[3 8 1 7 1 1 5 1 6 2 1 4 1]










[mean: 0.77456, std: 0.04832, params: {'estimator__loss': 'linear', 'estimator__learning_rate': 0.1, 'estimator__random_state': 0, 'estimator__n_estimators': 50}, mean: 0.77922, std: 0.05976, params: {'estimator__loss': 'linear', 'estimator__learning_rate': 0.1, 'estimator__random_state': 0, 'estimator__n_estimators': 100}, mean: 0.78223, std: 0.05846, params: {'estimator__loss': 'linear', 'estimator__learning_rate': 0.1, 'estimator__random_state': 0, 'estimator__n_estimators': 150}, mean: 0.78533, std: 0.05569, params: {'estimator__loss': 'linear', 'estimator__learning_rate': 0.1, 'estimator__random_state': 0, 'estimator__n_estimators': 200}, mean: 0.78868, std: 0.05527, params: {'estimator__loss': 'linear', 'e

In [118]:
#select best parameters and features for XGBOOST REGRESSOR
#it may take A LOOOOOOOT  of time depending on the dataset
# 15-30 mins on this dataset
from sklearn import feature_selection
from sklearn import pipeline
from sklearn.grid_search import GridSearchCV
from sklearn import linear_model


class MyPipe(pipeline.Pipeline):

    def fit(self, X, y=None, **fit_params):
        """Calls last elements .coef_ method.
        Based on the sourcecode for decision_function(X).
        Link: https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/pipeline.py
        ----------
        """
        super(MyPipe, self).fit(X, y, **fit_params)
        self.coef_ = self.steps[-1][-1].coef_
        return self



#X, y = make_friedman1(n_samples=50, n_features=10, random_state=0)

# Without Pipeline
clf2 =  xgb.XGBRegressor()




selector2 = feature_selection.RFE(clf2)
clf3 = GridSearchCV(selector2, param_grid={"estimator__max_depth":[2,3,4],"estimator__random_state":[0],"estimator__learning_rate":[0.1,0.5,1],"estimator__n_estimators":[50,100,150,200,250,300,350,400]},cv=5)
print("RUNNING")
clf3.fit(X_train,np.ravel(Y_train))

print("BEST PARAMETERS\n")
print(clf3.best_estimator_)
print("\nFEATURES_RANKING")
print(clf3.best_estimator_.n_features_,"feautres selected")


print(clf3.best_estimator_.ranking_)
print("\n\n\n\n")
print("\n\n\n\n")
print((clf3.grid_scores_))


RUNNING
BEST PARAMETERS

RFE(estimator=XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=2, min_child_weight=1, missing=None, n_estimators=200,
       n_jobs=1, nthread=None, objective='reg:linear', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=True, subsample=1),
  n_features_to_select=None, step=1, verbose=0)

FEATURES_RANKING
6 feautres selected
[1 8 5 7 1 1 2 1 6 1 3 4 1]










[mean: 0.84215, std: 0.04353, params: {'estimator__random_state': 0, 'estimator__learning_rate': 0.1, 'estimator__max_depth': 2, 'estimator__n_estimators': 50}, mean: 0.85043, std: 0.04515, params: {'estimator__random_state': 0, 'estimator__learning_rate': 0.1, 'estimator__max_depth': 2, 'estimator__n_estimators': 100}, mean: 0.84172, std: 0.04743, params: {'estimator__random_state': 0, 'estimator__learning_rate': 0.1, 'estimator__max_depth': 2, 'est